name: testml
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  onnxruntime:
    git:
      url: https://github.com/gtbluesky/onnxruntime_flutter.git
  ffi: ^2.0.1  # Pastikan ffi sudah ditambahkan

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/model.onnx
